version: '3.8'

services:
  web:
    build:
      context: ./container-build/web/
      dockerfile: Dockerfile
    container_name: ic-app
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${CI_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${CI_DB_IC_NAME}
      MYSQL_USER: ${CI_DB_IC_USERNAME}
      MYSQL_PASSWORD: ${CI_DB_IC_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql

    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
      UPLOAD_LIMIT: 300M
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
